export const allProducts = [
  {
    id: 1,
    name: "NebulaNode",
    slug: "nebulanode",
    tagline: "Global edge computing for decentralized apps",
    description:
      "A distributed infrastructure layer that deploys your serverless functions to over 300 points of presence globally in under 10ms.",
    websiteUrl: "https://nebulanode.io",
    tags: ["Infrastructure", "Edge", "Web3"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "atlas@nebula.io",
    votes: [{ userId: "user_1" }, { userId: "user_2" }],
  },
  {
    id: 2,
    name: "VelociGraph",
    slug: "velocigraph",
    tagline: "Real-time vector analytics for modern stacks",
    description:
      "High-performance graphing engine designed to visualize multi-dimensional data streams without lag or browser crashes.",
    websiteUrl: "https://velocigraph.app",
    tags: ["Data Viz", "Analytics", "SaaS"],
    createdAt: new Date("2024-03-05"),
    approvedAt: new Date("2024-03-06"),
    status: "approved" as const,
    submittedBy: "dev@velocigraph.app",
    votes: [{ userId: "user_3" }],
  },
  {
    id: 3,
    name: "GhostBuffer",
    slug: "ghostbuffer",
    tagline: "Universal state management for micro-frontends",
    description:
      "A lightweight, zero-dependency library that syncs state across different frameworks and browser tabs seamlessly.",
    websiteUrl: "https://ghostbuffer.dev",
    tags: ["Developer Tools", "JavaScript"],
    createdAt: new Date("2024-03-10"),
    approvedAt: new Date("2024-03-11"),
    status: "approved" as const,
    submittedBy: "ghost@dev.com",
    votes: [],
  },
  {
    id: 4,
    name: "SyncroPulse",
    slug: "syncropulse",
    tagline: "Automated heartbeat monitoring for cron jobs",
    description:
      "Never miss a silent failure again. SyncroPulse monitors your background tasks and alerts you via Slack if a job skips a beat.",
    websiteUrl: "https://syncropulse.com",
    tags: ["DevOps", "Monitoring", "SaaS"],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "admin@syncro.com",
    votes: [{ userId: "user_1" }, { userId: "user_4" }, { userId: "user_5" }],
  },
  {
    id: 5,
    name: "AetherFlow",
    slug: "aetherflow",
    tagline: "Low-code automation for creative workflows",
    description:
      "Connect your design tools, asset managers, and publishing platforms with a visual drag-and-drop canvas.",
    websiteUrl: "https://aetherflow.design",
    tags: ["No-Code", "Design", "Productivity"],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "pixel@aether.com",
    votes: [{ userId: "user_2" }, { userId: "user_6" }],
  },
  {
    id: 6,
    name: "KryptonDB",
    slug: "kryptondb",
    tagline: "The world's first encrypted-at-rest graph database",
    description:
      "Build complex relational maps without sacrificing privacy. Krypton uses zero-knowledge proofs to keep your data invisible to the host.",
    websiteUrl: "https://krypton.db",
    tags: ["Security", "Database", "Backend"],
    createdAt: new Date("2024-03-25"),
    approvedAt: new Date("2024-03-26"),
    status: "approved" as const,
    submittedBy: "sec@krypton.db",
    votes: [{ userId: "user_7" }],
  },
  {
    id: 7,
    name: "LuminaDash",
    slug: "luminadash",
    tagline: "Smart executive dashboards for remote teams",
    description:
      "Pull metrics from Jira, GitHub, and Stripe into a single, beautiful dashboard that updates in real-time.",
    websiteUrl: "https://lumina.so",
    tags: ["Business", "Productivity", "Management"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "team@lumina.so",
    votes: [{ userId: "user_4" }, { userId: "user_8" }],
  },
  {
    id: 8,
    name: "OmniShader",
    slug: "omnishader",
    tagline: "Cloud-based GPU rendering for the web",
    description:
      "Offload heavy WebGL and 3D processing to our high-performance GPU clusters for instant rendering on any device.",
    websiteUrl: "https://omnishader.xyz",
    tags: ["3D", "Cloud Rendering", "Infrastructure"],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "poly@omni.xyz",
    votes: [{ userId: "user_1" }, { userId: "user_3" }, { userId: "user_7" }],
  },
];
